### ISSUE TITLE
What's going on?

### ISSUE THREAD

**Issue by SuperOP535** [uNetworking/uWebSockets-node#1]
Literally, what's going on?
- Some months ago the bindings repo was removed (not a problem since it was still avaliable on npm)
- Npm stopped being used (why??)
- Bindings repo returned
- Bindings repo disappeared
- This empty repo appeared

(unrelated)
- I can no longer find the gitter (maybe I'm just bad at searching but I wanted to tell you this in gitter)

**Comment by 4ver** [comment]
See https://www.reddit.com/r/node/comments/91kgte/uws_has_been_deprecated/

**Comment by alexhultman** [comment]
@4ver BenjiSponge in that Reddit thread made a pretty accurate analysis of how I work and think.

If you want a more in depth briefing of what's going on I'm afraid that info is only available to sponsors.

**Comment by alexhultman** [comment]
From that Reddit thread by some third-party moron:

> Libertarians should realize that once you hand out something to the public it's no longer your personal property and they can do with it what they please. Trying to become the authority of the use or control of the thing you gave away is pretty authoritarian... don't you think?

I hope you all realize this already but nobody is "giving away" anything here. **I own** copyright on 95-99% of this project except for some minor tweaks here and there. This project is my intellectual property and I may do with it what ever I feel like.

**You may** use my intellectual property under the Zlib **license**. Failure to comply with this **license** (including clause 2) constitutes a breach and is thus copyright infringement.

Please learn some basic copyright law before projecting your utopian socialist gut feelings on well-defined IP laws.

**Comment by ohenepee** [comment]
@alexhultman I think its high time you cooled down... a significant population of the developer world are just pretty much d**ks... almost everyone wants speed but won't do anything about it and will even make up silly excuses for why they are slow or using or building something that's slow. And the moment someone builds something that's fast, all hell breaks lose... first it was [this guy](https://github.com/Helidium/Mitol), now its NPM (the suckverse of all package manager multiverses). 2017 and 2018 has proved to me beyond belief that this world is indeed a controlled system (by some seemingly connected elites/people).

You Alex should know that if your users hated your work or you as a matter of fact, your stars would've dropped significantly by 30% (at least). Please cool down and do what you do! Suckers get born everyday.

**Comment by alexhultman** [comment]
I don't know what you mean by liking to Mitol but it serves perfect example of my message:

Mitol is a fork of my project. You can find this information by looking in his license. He did not list this at first, so I DMCA:Ed his repo. Yet another perfect example of my sole retained copyright.

> 2017 and 2018 has proved to me beyond belief that this world is indeed a controlled system (by some seemingly connected elites/people).

It took you this long? How old are you? Communism fell in 1991, roughly the entire world now employ some variation of capitalism.

> your stars would've dropped significantly by 30% (at least). Please cool down and do what you do!

GitHub stars..... You think I pay my rent with GitHub stars? Are you serious? GitHub... stars? What in the world is wrong with you? You expect me to work for free, nay, for GitHub stars? Holy shit kid grow up and get a job.

**Comment by alexhultman** [comment]
Yes hello, KLM? I would like to fly to Spain, how many GitHub stars would that be? What!? You don't accept GitHub stars as currency? Oh, why I need to reconsider my life decisions a bit then, thanks..

**Comment by alexhultman** [comment]
I wonder how many paternity leave months 500 GitHub stars is? Do I get dental and pension or is that an extra option? What about gym membership? Is that included? How do I taxate GitHub stars?

**Comment by girng** [comment]
@alexhultman never stop
